version: '3.8'

services:
  neo4j:
    image: neo4j:5.18.0
    container_name: graphrag_neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/conf:/var/lib/neo4j/conf
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_PLUGINS=["graph-data-science", "apoc"]

  postgres:
    image: postgres:15.6-alpine
    container_name: graphrag_postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=graphrag_meta

  redis:
    image: redis:7.2-alpine
    container_name: graphrag_redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data

  minio:
    image: minio/minio:RELEASE.2024-10-13T13-34-11Z
    container_name: graphrag_minio
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    volumes:
      - ./minio/data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"